### ISSUE TITLE
VideoIn in not working 2022.5.0-0168

### ISSUE THREAD

**Issue by phlegma** [vvvv/VL.Video.MediaFoundation#14]
Just sumpled over this by testing Imgui with vvvv version 2022.5.0-0168.

Steps:

    * Adding package VL.Video.Mediafoundation
    * Create VideoIn. Skia or Stride.
    * Node throws "Method not found "Error

![grafik](https://user-images.githubusercontent.com/358332/181562118-3b599ef0-f84c-4aab-9cb1-8c53ecda4f72.png)

Is there any how to to update libs to .net6 to do it by it own?

**Comment by azeno** [comment]
Woa, turned out the wrong dll was selected by the build system. SharpDX.Mediafoundation delivers dlls for net45, net40 and netstandard1.1 - when using net6 as a build target, dotnet will select the netstandard1.1 dll. So far so good, but turned out that particular dll is missing some methods (there's probably a reason..) hence the MethodNotFoundException. In any case, found a workaround by manually including the right dll when we build vvvv.exe

Should therefor work in upcoming previews.

Thanks for the report!
